### ISSUE TITLE
sorting wrong when dates include month

### ISSUE THREAD

**Issue by dtfitch** [HanZhang-psych/CV#4]
first off, thank you so much for adapting this great package to APA. I've been working with your code and I can't seem to get the conference proceedings in descending order when month is included (I need to report month for conference proceedings). For example when I add month to your first two proceedings like this:
`@inproceedings{zhang_scan-paths_2020,
	location = {Chicago, {IL}, {USA}},
	title = {Scan-paths of Mind-wandering during Real-world Scene Perception},
	eventtitle = {Talk to be presented at the 92nd Annual Meeting of the Midwestern Psychological Association},
	author = {{\bf Zhang}, Han and Anderson, Nicola C. and Miller, Kevin F.},
	date = {2020-01},
	pubstate = {{\bf Graduate Student Research Award}}
}

@inproceedings{zhang_reduced_2019,
	location = {Montreal, Canada},
	title = {Reduced Re-reading of Garden-path Jokes during Mindless Reading},
	eventtitle = {Poster presented at the 60th Psychonomic Society Annual Meeting},
	author = {{\bf Zhang}, Han and Qu, Chuyan and Miller, Kevin F. and Cortina, Kai S.},
	date = {2019-09}
}`
and knit your CV...you will first note that those two items will now drop to the bottom (I presume that is because of the numeric coding of date when some include month and some do not). But also that the September 2019 presentation is above the January 2020 presentation. They seem to be descending by month first, then year. any idea why? This may be a bug in apa-cv.csl, but I thought I'd check with you first before posting there. thanks!

**Comment by HanZhang-psych** [comment]
Hi!

Thanks for bringing up this issue. It seems that changing line 1441 of `apa-cv.csl` from `<key macro="date-sort-date" sort="descending"/>` to `<key variable="issued" sort="descending"/>` can fix the problem. 

I have added month to my conference presentations to reflect this change. Let me know if this solves your problem.

Han

**Comment by dtfitch** [comment]
Yep, fixed it for me. thanks!  I also noticed that "location" wasn't showing up until you changed it to "note" in your Presentations.bib file. I'm very new to these standards, and although I think location is a much better label, it seems like the standards don't use location.

thanks again!
Dillon

**Comment by HanZhang-psych** [comment]
Interestingly, changing it to "note" didn't work for me, although changing it to "venue" did. Yes, the standards are quite confusing to me as a beginner. Anyway, I updated the files again to add the conference locations. Thanks!
